"""
CAPSS - Context-Aware Privacy Protection and Scheme Selection

File:
    request_classifier.py

Purpose
-------
Combines the outputs of all validators and detectors
to produce the final Pre-AMF decision.

The classifier contains NO validation logic.

It only consumes the outputs generated by:

    Header Validator
    Parameter Validator
    Subscriber Validator
    Duplicate Detector
    Rate Monitor

and produces the final decision.

Possible Decisions
------------------
ALLOW
TAG
BLOCK
"""

from systems.pre_amf.attack_rules import (
    ALLOW,
    TAG,
    BLOCK,

    NORMAL,
    SUSPICIOUS,
    MALICIOUS,

    ATTACK_NONE,
    ATTACK_INVALID_HEADER,
    ATTACK_INVALID_PARAMETER,
    ATTACK_INVALID_SUBSCRIBER,

    MESSAGE_VALID_REQUEST,
)

from systems.pre_amf.models import (
    ValidationContext,
    ClassificationResult,
)

SEVERITY_ORDER = {
    NORMAL: 0,
    SUSPICIOUS: 1,
    MALICIOUS: 2,
}

class RequestClassifier:
    """
    Final decision engine for the
    Pre-AMF Security Layer.
    """

    def classify(
        self,
        context: ValidationContext,
    ) -> ClassificationResult:

        reasons = []

        decision = ALLOW

        severity = NORMAL

        attack_flag = False

        attack_type = ATTACK_NONE

        # ==================================================
        # Header Validation
        # ==================================================

        if not context.header_result.passed:

            attack_flag = True

            decision = BLOCK

            severity = MALICIOUS

            attack_type = ATTACK_INVALID_HEADER

            reasons.extend(
                context.header_result.errors
            )

            context.statistics.invalid_headers += 1

        # ==================================================
        # Parameter Validation
        # ==================================================

        if not context.parameter_result.passed:

            attack_flag = True

            decision = BLOCK

            severity = MALICIOUS

            attack_type = ATTACK_INVALID_PARAMETER

            reasons.extend(
                context.parameter_result.errors
            )

            context.statistics.invalid_parameters += 1

        # ==================================================
        # Subscriber Validation
        # ==================================================

        if not context.subscriber_result.passed:

            attack_flag = True

            decision = BLOCK

            severity = MALICIOUS

            attack_type = ATTACK_INVALID_SUBSCRIBER

            reasons.extend(
                context.subscriber_result.errors
            )

            context.statistics.invalid_subscribers += 1
        
        # ==================================================
        # Registration Flood
        # ==================================================

        if context.rate_result and context.rate_result.detected:

            attack_flag = True

            decision = BLOCK

            severity = MALICIOUS

            attack_type = context.rate_result.attack_type

            reasons.append(
                context.rate_result.message
            )

            context.statistics.flood_attacks += 1
        
        # ==================================================
        # Duplicate Detector
        # ==================================================

        # Only process duplicate/replay if a flood has NOT
        # already been detected.

        if (
            context.duplicate_result.detected
            and
            not context.rate_result.detected
        ):

            attack_flag = True

            if decision != BLOCK:

                decision = TAG

            SEVERITY_ORDER = {
                NORMAL: 0,
                SUSPICIOUS: 1,
                MALICIOUS: 2,
            }

            if (
                SEVERITY_ORDER[context.duplicate_result.severity]
                > SEVERITY_ORDER[severity]
            ):
                severity = context.duplicate_result.severity

            attack_type = context.duplicate_result.attack_type

            reasons.append(
                context.duplicate_result.message
            )

            context.statistics.duplicate_attacks += 1

            if attack_type == "REPLAY":

                context.statistics.replay_attacks += 1

        # ==================================================
        # Default Reason
        # ==================================================

        if not reasons:

            reasons.append(
                MESSAGE_VALID_REQUEST
            )

        # ==================================================
        # Statistics
        # ==================================================

        context.statistics.total_requests += 1

        if decision == ALLOW:

            context.statistics.allowed += 1

        elif decision == TAG:

            context.statistics.tagged += 1

        else:

            context.statistics.blocked += 1
    
        # ==================================================
        # Remove duplicate reasons
        # ==================================================

        reasons = list(dict.fromkeys(reasons))

        # ==================================================
        # Final Result
        # ==================================================
    
        result = ClassificationResult(

            decision=decision,

            attack_flag=attack_flag,

            attack_type=attack_type,

            severity=severity,

            reasons=reasons

        )

        context.classification_result = result

        return result


# ==========================================================
# Convenience Function
# ==========================================================

def classify_request(
    context: ValidationContext,
) -> ClassificationResult:
    """
    Convenience wrapper.
    """

    classifier = RequestClassifier()

    return classifier.classify(context)